 
 BEGIN;

 DROP TABLE IF EXISTS "user", "recipe";

 CREATE TABLE "user" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" TEXT UNIQUE NOT NULL,
    "username" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "is_admin" BOOLEAN NOT NULL DEFAULT FALSE
 );

 CREATE TABLE "recipe" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" TEXT NOT NULL,
    "ingredients_list" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "cooking_time" INT,
    "difficulty" TEXT,
    "rate" INT,
    "picture" TEXT
 );

 COMMIT;