 
 BEGIN;

 DROP TABLE IF EXISTS "users", "recipes";

 CREATE TABLE "users" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" VARCHAR(128) UNIQUE NOT NULL,
    "username" VARCHAR(128) NOT NULL,
    "password" VARCHAR(128) NOT NULL,
    "is_admin" BOOLEAN NOT NULL DEFAULT FALSE
 );

 CREATE TABLE "recipes" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" VARCHAR(128) NOT NULL,
    "ingredients_list" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "steps" TEXT NOT NULL,
    "cooking_time" INT,
    "difficulty" VARCHAR(32),
    "rate" INT,
    "picture" TEXT
 );

 COMMIT;